language: java
script:
- gradle build
deploy:
  provider: heroku
  api_key:
    secure: e7f6d97e-4ba4-4227-b534-fa4d3268b847
  app: petadoption-backend
  on: 
    repo: McGill-ECSE321-Winter2020/project-group-12
