language: java
script:
- gradle build
deploy:
  provider: heroku
  api_key:
    secure: "JNG6D2EUoKmRtiPzXE73PxXzoRZ9BTy9ASfo2JMy3zYrnBLByZlAS1YliTGaYTZKSdSs65vwnCiOGTunyjC34bcZgBw1mi0OmOO+iJXBT3BcRzP5n5lVgSz6gOOJq3LPsyRZlZsBC0z99B3VsPN4R7btGTBeaE5t6Z+KPnlfdpLsqqV/nOv3sXD3BU9MuUriJopwhZJo61FH9Rxv0eRODK+6ii63JJ/30jGDKEeWFNWZOfQkyIX/yvyaT+4VvRgp5gWPIHCeDFGsuj3VR9RXvRDUFpQX7XSr9hJtC6Q9yszVcWDdEzK/BWHCGV666o0gahW9mbqjC9IGpUZUAxs29cMyqQINeLzrXxBFqwYotxcLjnMXlr1YjK6xPkm6DFXwZpwnx7fWk+CS0ADVCMqVKvUtLxXknKCClqOx5bb8mbTWys8/Un2DvIAlaTnGfepCUXTkcM7wqfAtiZZxm664Gq9z1eh17joOdhxEnR61Ul6MUT4TD2u+TigMs8yktmGGIUbnwXg1PVIyb8dmrds8pDvFQDedlsWI0DPehIbaX3/BBoj3ikpLMA+BBAWGvh2myO+SpsDG6hszt0fL1du5yJiRb0JfQYV49Vz8o7w0RE3Esrs3rWufD5WTE276VdHutzrjg5+wP52V61cz7JC6VxAUJT+PO3rz2BssqK6GtYc="
  app: petadoption-backend
  on: master
